server {
    listen 80;
    server_name localhost;

    # Serve static React UI files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Route logic for Single Page Applications (React/Vite)
        try_files $uri $uri/ /index.html;
    }
}
